### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by rpodcast** [sainathadapa/stubthat#2]
Hello, I'd like to start using this package in my automated testing workflow, but I won't be able to install it within my company unless it is released under an open-source license.  Is there any chance you will change the license to something like GPL, MIT, etc?

**Comment by rpodcast** [comment]
Scratch that, I did not read your DESCRIPTION file  carefully enough, I see it is under the MIT license.  Sorry!

**Comment by sainathadapa** [comment]
Cool. I was about to reply when you closed the issue, Good to know that someone is going to use the package!
