### ISSUE TITLE
expect calls?

### ISSUE THREAD

**Issue by dchudz** [sainathadapa/stubthat#3]
This package looks great, thanks!

It'd be great if it were easy to `expect` that the stub was called a certain number of times or with certain arguments.

**Comment by sainathadapa** [comment]
An expectation to check the number of times a stub is called, was initially planned. Along the way during development, we forgot about it. It should be easy to add that. Will do in the next few days.

As to checking for certain arguments, `withArgs` should suffice, isn't it?

**Comment by dchudz** [comment]
Thanks!

I was thinking of `expect`ing that the stub was called first with `x=5`, and then with `x=5, y=10`, similar to Python's:

```
In [7]: ?mock.MagicMock.assert_called_with
Signature: mock.MagicMock.assert_called_with(_mock_self, *args, **kwargs)
Docstring:
assert that the mock was called with the specified arguments.

Raises an AssertionError if the args and keyword args passed in are
different to the last call to the mock.
```

I suppose `withExactArgs` is similar, but only if you want to separately specify the return value for each set of arguments.

**Comment by sainathadapa** [comment]
I'm sorry but didn't understand your comment clearly. Isn't what you are asking for is same as

```
stub$onCall(1)$withArgs(x = 5)$returns(1)
stub$onCall(2)$withExactArgs(x = 5, y = 10)$returns(2)
```

**Comment by dchudz** [comment]
Sorry I've been confusing.

What I meant is really the combination of:
- `stub$expects`
- asserting that the stub was called
- extending `onCall` so that `stub$onCall(1)$expects(x=6)` works

So most of the pieces are there.

Thanks for the package!

**Comment by sainathadapa** [comment]
Now I understand. Thanks!

**Comment by sainathadapa** [comment]
@dchudz I have updated the master branch with requested functionality. Here are the changes from v0.1.0 :
- `stub$onCall(...)$withArgs(..)` is now `stub$onCall(...)$expects(..)`. Previously the stub didn't throw an error if the specified arguments are not present on the nth call. Now it does.
- `stub$onCall(...)$withExactArgs(..)` is now `stub$onCall(...)$strictlyExpects(..)`. Same reason as above.
- `stub$expects(...)` is now `stub$strictlyExpects(...)`.
- New `stub$expects(...)` checks if the expected arguments are **part** of the function call (not **exact** set).
- New `stub$calledTimes()` to get the number of times the function was called.
- No need for `stub$build()` anymore. Mock is directly available from `stub$f`

Can you check the functionality and close the issue? You can install the development version by doing `devtools::install_github("sainathadapa/stubthat")`. Thanks.

**Comment by dchudz** [comment]
Perfect, thanks! I gave it a try and it looks great.

One more thought: It seems like it might be better to be more strict about positional arguments when we were expecting a keyword argument. I expected this to fail:

```
f <- function(x = 1, y = 2) return(x + y)
f_stub <- stub(f)
f_stub$expects(x = 4)
f_stub$f(4)
```

**Comment by sainathadapa** [comment]
`stub$expects` in v0.1.0 is now `stub$strictlyExpects`.
This will fail:

``` r
f <- function(x = 1, y = 2) return(x + y)
f_stub <- stub(f)
f_stub$strictlyExpects(x = 4)
f_stub$f(4)
```

I have also updated and expanded the readme with examples. Do take a look.

**Comment by dchudz** [comment]
Looks great!
