### ISSUE TITLE
Host with_mock()?

### ISSUE THREAD

**Issue by krlmlr** [sainathadapa/stubthat#7]
The with_mock() function seems to interact badly with the JIT compiler:

- The JIT compiler uses base functions, if they are mocked the JIT compiler breaks (?, https://github.com/hadley/testthat/issues/543#issuecomment-267969779)
- Cannot mock inlined functions (https://github.com/hadley/testthat/issues/546#issuecomment-267858869)

It looks like mocking is only safe (if at all) for functions defined in the package under test. The current implementation of testthat::with_mock() will be broken soon (https://github.com/hadley/testthat/pull/553), this is a good opportunity to move this function elsewhere. I think stubthat would be a good place, would you agree to host a modified version?

**Comment by sainathadapa** [comment]
Sure, but I am not familiar with the internals of R, in this case especially the functionality regarding the JIT compiler. Unless someone can help me in updating the implementation (or at least specifying cases where `with_mock` will not work so that I can stop the `with_mock` function being used in such cases), I'll not be able to maintain the `with_mock()` function in this package.

**Comment by nsfinkelstein** [comment]
As I mentioned in https://github.com/hadley/testthat/issues/546#issuecomment-267858869, [mockery](github.com/n-s-f/mockery) already has a replacement function for `with_mock` called `stub`, which takes a different approach to mocking things out that is not restricted by the issues raised in the other threads. If `with_mock` breaks, I think this package would work just as well with mockery. I also think mockery would be a reasonable place to house `with_mock`, where it could live alongside `stub` for legacy reasons.

**Comment by krlmlr** [comment]
Thanks. I have mixed feelings about hosting `with_mock()` in a package that imports `testthat`, because `testthat` will use this function for its own tests. This kind of dependency cycle is not forbidden, though.

One other minor issue is that the [implementation](https://github.com/krlmlr/mockr) is currently split over 6 code modules; we might as well do it in one file, and indicate the splits with regions or something similar.

**Comment by sainathadapa** [comment]
ok!
